### ISSUE TITLE
Cubase don't recognize the file

### ISSUE THREAD

**Issue by edemunari** [bjoluc/cubase-xtouch-midiremote#3]
Cubase can't load the file, on mac os x Catalina, it is greyed.
Cheers, Eriberto

**Comment by bjoluc** [comment]
Hi @edemunari,
I can only ask you some generic questions:
* Are you using Cubase 12.0.52?
* Are there any errors shown in the MIDI Remote Script Console?
* Could you post a screenshot of the MIDI Remote Manager's Scripts tab?

**Comment by edemunari** [comment]
Yep sure.
1. Yes

Sorry trying to make some screenshot I understand that because the script
is loaded I have to make the control panel by myself, you says this but I
Wasn't aware of what it means... now it's all right...

Cheers. Eriberto




Il giorno sab 11 mar 2023 alle ore 11:59 bjoluc ***@***.***>
ha scritto:

**Comment by bjoluc** [comment]
Great to hear you got it working!

> I have to make the control panel by myself, you says this but I
Wasn't aware of what it means...

If you have any suggestions on how to make the documentation more comprehensible, I'm happy to update the readme!
