### ISSUE TITLE
Cubase randomly swaps MIDI ports

### ISSUE THREAD

**Issue by bjoluc** [bjoluc/cubase-xtouch-midiremote#4]
Hi,
New issue...it seems like the script or cubase api "lost" the midi ports defined at the set up !
![Capture d’écran 2023-03-16 143443](https://user-images.githubusercontent.com/125523762/225634052-77a37642-3cba-4e96-ba0c-7756de73f5ea.jpg)
![Capture d’écran 2023-03-16 143517](https://user-images.githubusercontent.com/125523762/225634078-e474fe5d-810e-49d5-a2e2-81d87b35a6e1.jpg)
the midi ports were in and out in the same order at set up ... xtouch ext, xtouch, and Desktop....
but at the next start up of cubase project...the midi out ports seem to be unordered and, at this moment, the first extender ( called stouch-ext ) doesn't work properly anymore....it show the tarcks names but not colors....

_Originally posted by @limageurpublic in https://github.com/bjoluc/cubase-xtouch-midiremote/discussions/1#discussioncomment-5334656_

**Comment by bjoluc** [comment]
Thanks for flagging this @limageurpublic! I suspect this might happen due to duplicate internal MIDI Remote API port names. Let me write a potential fix tomorrow. When would you be available for testing it with your setup?

**Comment by limageurpublic** [comment]
Hi, I'll be free between 11am and 15am max
